### ISSUE TITLE
`session.lightcurve` fails due to some plates with marker values (ra=999, dec=99)

### ISSUE THREAD

**Issue by hamogu** [pkgw/daschlab#20]
I'm using DASCH for "SU Aur". (I'm doing the analysis in a jupyter labs following the example notebook, but I **think** that the following code is minimal to reproduce it):
```Python
import daschlab
sess = daschlab.open_session(source="SU Aur")
sess.select_target(name="SU Aur")
sess.select_refcat("apass")
lc = sess.lightcurve(3).   # It failed with target_id 0, so I tried a couple other numbers. The output below is for target_id=3
                                         # though I suspect that the exact number is not important - if a plate has no valid RA/DEC 
                                         # it won't work independent of which target number I put in here.
```
This fails with a long error message, which I will append below, but some interactive debugging traces it down to a few plates that are, for some reason, in the list of retrieved data, although they do not have valid RA/DEC entries. 
```
ipdb>  np.array(input_cols["ra"])[[6916, 6976, 7018]]

array([999., 999., 999.])

ipdb>  np.array(input_cols["dec"])[[6916, 6976, 7018]]

array([99., 99., 99.])

ipdb>  table[[6916, 6976, 7018]]

<Plates masked=True length=3>
series platenum scannum mosnum expnum solnum class
 str4   uint32   uint8  uint8  uint8  uint8   str7
------ -------- ------- ------ ------ ------ -----
    rh    11889       0      0      1      1     M
    rh    12036       0      0      1      1     M
    rh    12202       0      0      1      1     M
```

Why these plates are included in the list that is retrieved, I do not know, but I do know that `dec=99` will make the astropy coordinate function fail:
```Python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], line 6
      1 # the refcat sources are sorted by proximity to our search location
      2 # and assigned "local ID" numbers sequentially. So, target #0 is
      3 # almost always the one that you're interested in.
      4 TARGET_ID = 0
----> 6 lc = sess.lightcurve(3)
      7 # We'll explore the lightcurve object in more detail soon.
      8 # Also, this manual analysis is superseded by `sess.plates().candidate_nice_cutouts()`

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/__init__.py:553](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/__init__.py#line=552), in Session.lightcurve(self, src_ref)
    550 src = self._resolve_src_reference(src_ref)
    552 # We're going to need this later; emit the output now.
--> 553 plates = self.plates()
    555 name = src["ref_text"]
    556 lc = self._lc_cache.get(name)

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/__init__.py:477](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/__init__.py#line=476), in Session.plates(self)
    475 t0 = time.time()
    476 print("- Querying API ...", flush=True)
--> 477 self._plates = _query_plates(self._query.pos_as_skycoord(), PLATES_RADIUS)
    478 self._plates.meta["daschlab_sess_key"] = str(self._root)
    480 with self._save_atomic("plates.ecsv") as f_new:

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/plates.py:1028](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/plates.py#line=1027), in _query_plates(center, radius)
   1024 def _query_plates(
   1025     center: SkyCoord,
   1026     radius: u.Quantity,
   1027 ) -> Plates:
-> 1028     return _postproc_plates(_get_plate_cols(center, radius))

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/plates.py:1152](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/daschlab/plates.py#line=1151), in _postproc_plates(input_cols)
   1150 table["solnum"] = mc("solnum", np.uint8)
   1151 table["class"] = input_cols["class"]
-> 1152 table["pos"] = SkyCoord(
   1153     ra=input_cols["ra"] * u.deg,
   1154     dec=input_cols["dec"] * u.deg,
   1155     frame="icrs",
   1156 )
   1157 table["exptime"] = np.array(input_cols["exptime"], dtype=np.float32) * u.minute
   1158 table["obs_date"] = Time(input_cols["jd"], format="jd")

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/sky_coordinate.py:351](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/sky_coordinate.py#line=350), in SkyCoord.__init__(self, copy, *args, **kwargs)
    347 # Parse the args and kwargs to assemble a sanitized and validated
    348 # kwargs dict for initializing attributes for this object and for
    349 # creating the internal self._sky_coord_frame object
    350 args = list(args)  # Make it mutable
--> 351 skycoord_kwargs, components, info = _parse_coordinate_data(
    352     frame_cls(**frame_kwargs), args, kwargs
    353 )
    355 # In the above two parsing functions, these kwargs were identified
    356 # as valid frame attributes for *some* frame, but not the frame that
    357 # this SkyCoord will have. We keep these attributes as special
    358 # skycoord frame attributes:
    359 for attr in skycoord_kwargs:
    360     # Setting it will also validate it.

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/sky_coordinate_parsers.py:229](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/sky_coordinate_parsers.py#line=228), in _parse_coordinate_data(frame, args, kwargs)
    225 units = _get_representation_component_units(args, kwargs)
    227 # Grab any frame-specific attr names like `ra` or `l` or `distance` from
    228 # kwargs and move them to valid_components.
--> 229 valid_components = _get_representation_attrs(frame, units, kwargs)
    231 # Error if anything is still left in kwargs
    232 if kwargs:
    233     # The next few lines add a more user-friendly error message to a
    234     # common and confusing situation when the user specifies, e.g.,
    235     # `pm_ra` when they really should be passing `pm_ra_cosdec`. The
    236     # extra error should only turn on when the positional representation
    237     # is spherical, and when the component 'pm_<lon>' is passed.

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/sky_coordinate_parsers.py:566](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/sky_coordinate_parsers.py#line=565), in _get_representation_attrs(frame, units, kwargs)
    564 if value is not None:
    565     try:
--> 566         valid_kwargs[frame_attr_name] = repr_attr_class(value, unit=unit)
    567     except u.UnitConversionError as err:
    568         error_message = (
    569             f"Unit '{unit}' ({unit.physical_type}) could not be applied to"
    570             f" '{frame_attr_name}'. This can occur when passing units for some"
   (...)
    574             " components."
    575         )

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/angles/core.py:604](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/angles/core.py#line=603), in Latitude.__new__(cls, angle, unit, **kwargs)
    602     raise TypeError("A Latitude angle cannot be created from a Longitude angle")
    603 self = super().__new__(cls, angle, unit=unit, **kwargs)
--> 604 self._validate_angles()
    605 return self

File [~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/angles/core.py:635](http://localhost:8888/lab/tree/projects/~/mambaforge/envs/daschlab/lib/python3.12/site-packages/astropy/coordinates/angles/core.py#line=634), in Latitude._validate_angles(self, angles)
    632     angles_view = angles_view[np.newaxis]
    634 if np.any(np.abs(angles_view) > limit):
--> 635     raise ValueError(
    636         "Latitude angle(s) must be within -90 deg <= angle <= 90 deg, "
    637         f"got {angles.to(u.degree)}"
    638     )

ValueError: Latitude angle(s) must be within -90 deg <= angle <= 90 deg, got [27.833741 32.619993 48.173171 ... 30.005875 30.024569 29.024569] deg
```

**Comment by fklich** [comment]
Hello Hans:
  Thanks for your posting on the above Daschlab issue.  I experienced the same for M81.
Just to be clear, you were able to identify the bogus RA and Dec values.........did you then eliminate these unusable plates and move forward with the rest of your analysis?  I'm seeking/hoping to do same.  Peter Williamson explained that you had also encountered this problem.
Fred Klich
CU Boulder

**Comment by hamogu** [comment]
@fklich No, I just run into the issue, identified the problem and stopped there. As it turns out, my target is not quite as interesting as I thought, so I'll get back to it later.

**Comment by fklich** [comment]
okay, thanks for the feedback.  I'm going to attempt an ad-hoc cleanup of the lc object and see if I can get it to run.  I'll let you know how it goes.
Fred Klich

**Comment by pkgw** [comment]
I have addressed this bug in #22. If you update your installation to use the most recent version of the code, hopefully it'll be dealt with.

The main purpose of #22 was to add some new code to [merge lightcurves][1] to address the [source-splitting issue][2]. It's still lightly-tested, but in at least one test case it seems to be working well, helping to recover a 7.53-day period for HD 5501.

[1]: https://daschlab.readthedocs.io/en/latest/api/daschlab.lightcurves.merge.html#daschlab.lightcurves.merge
[2]: https://dasch.cfa.harvard.edu/drnext/ki/source-splitting/

If one of you can verify that the latest code fixes the issue, we can go ahead and close this, I think.

**Comment by fklich** [comment]
Peter  Thanks, I will perform a test tomorrow by 2400 MST!Regards,Fred klichSent from my iPhoneOn Jul 23, 2024, at 2:18 PM, Peter Williams ***@***.***> wrote:﻿
I have addressed this bug in #22. If you update your installation to use the most recent version of the code, hopefully it'll be dealt with.
The main purpose of #22 was to add some new code to merge lightcurves to address the source-splitting issue. It's still lightly-tested, but in at least one test case it seems to be working well, helping to recover a 7.53-day period for HD 5501.
If one of you can verify that the latest code fixes the issue, we can go ahead and close this, I think.

**Comment by fklich** [comment]
Peter,
  I have not conducted a successful test yet:

  1.
Started terminal session
  2.
conda activate daschlab
  3.
pip install git+https://github.com/pkgw/daschlab.git

The pip install showed no errors.  After starting with a fresh terminal session and daschlab environment, the test still did not work, resulting in the same error.

I'm retracing my steps......seeking verification that these components were updated; I'm dusting off my github skills, thinking I should be able to update directly from github environment.
Fred Klich

[cid:260d03d3-c17a-4bf7-b143-8431a8a94535]

________________________________

**Comment by fklich** [comment]
Hey Peter,
  For step 2 below, should I be referring to the url for this specific update:::???

  1.
pip install git+https://github.com/pkgw/qxcas-fix.

.......I hope I'm correct.......hoping the dust on my github skills is dimishing...
Many thanks,
Fred Klich



________________________________
From: Fred Klich ***@***.***>
Sent: Wednesday, July 24, 2024 6:29 PM
To: pkgw/daschlab ***@***.***>
Subject: Feecback WRT ====>>>>Re: [pkgw/daschlab] `session.lightcurve` fails due to some plates with marker values (ra=999, dec=99) (Issue #20)

Peter,
  I have not conducted a successful test yet:

  1.
Started terminal session
  2.
conda activate daschlab
  3.
pip install git+https://github.com/pkgw/daschlab.git

The pip install showed no errors.  After starting with a fresh terminal session and daschlab environment, the test still did not work, resulting in the same error.

I'm retracing my steps......seeking verification that these components were updated; I'm dusting off my github skills, thinking I should be able to update directly from github environment.
Fred Klich

[cid:260d03d3-c17a-4bf7-b143-8431a8a94535]

________________________________

**Comment by pkgw** [comment]
@fklich No, you should keep on using the `.../daschlab.git` URL. You may need to add a `-U` argument to the `pip install` command, though — does that help?

**Comment by fklich** [comment]
Thx  I will try your suggestion later this evening!Fred klichSent from my iPhoneOn Jul 25, 2024, at 6:06 AM, Peter Williams ***@***.***> wrote:﻿
@fklich No, you should keep on using the .../daschlab.git URL. You may need to add a -U argument to the pip install command, though — does that help?

**Comment by pkgw** [comment]
Be advised that with the merger of #24 , some fundamental terms in the code have changed. Basically, "plate" becomes "exposure" almost everywhere. This is going to be a bit of a disruptive change but it's necessary, so I wanted to get things right sooner rather than later.

**Comment by fklich** [comment]
Thank you Peter...... Your terminology change actually makes sense.
I'll assume that #24 will be stable enough to "update" at this time.
Fred Klich
PS - Sorry, my github email/id is not same as my CU Boulder id.......I may change that soon, as some of my class mates who work on github do use their CU id.

________________________________

**Comment by pkgw** [comment]
Fred reported separately that this bug indeed seems to be fixed, so I'll close this issue.
