### ISSUE TITLE
add `__version__` attribute to top level

### ISSUE THREAD

**Issue by hamogu** [pkgw/daschlab#21]
When reporting #1 I was looking to print out the version of daschlab I have installed, in the same way I woudl get e.g. the astropy or numpy version. 
```Python
import daschlab
import numpy
import astropy
print('numpy:' ,numpy.__version__)
print('astropy:', astropy.__version__)

numpy: 1.26.4
astropy: 6.1.1
```
However, daschlab does not have that attribute:
```Python
daschlab.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 1
----> 1 daschlab.__version__

AttributeError: module 'daschlab' has no attribute '__version__'
```

The documentation for daschlab includes installing directly from github, so some people may pull a newer development version etc., I recommend to define a version attribute to help find out what's going on when you receive bug reports and error messages.
Personally, I recommend [setuptools-scm](https://github.com/pypa/setuptools_scm) which will generate the version tag automatically when building a distribution or installing directly fomr a git checkout and what is used by e.g. astropy and other major projects in our ecosystem.

**Comment by pkgw** [comment]
Solved today!
